export class AppConfig {

    // Implement environments here ...
    // public static API_URL: string = "http://54.87.135.162:8000"; // To point to prod...
    public static API_URL: string = "https://localhost:7131"; // To work locally
}
